# Site settings
title: Susanga Video Team
tagline: And Tagline
email: webcreatelk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Susanga Video team official website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://svtlive.com" # the base hostname & protocol for your site
# url: "http://localhost:3000" # the base hostname & protocol for your site
logourl: /assets/images/susanga-logo.jpg # Site logo
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  # Social media links, leave blank to ignore
  social: 
    github: web-create
    twitter: webcreatelk
    facebook: webcreatelk
    gplus: +WebcreateLk
    dribble: webcreatelk
    pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
